version: '3.9'

services:
  db:
    container_name: tipen-demo-db
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-postgres}
      - POSTGRES_DB=${DB_NAME:-tipen-demo-db}
      - DATABASE_HOST=${DB_HOST}

    networks:
      - db
    ports:
      - 5434:5432
    env_file:
      - .env
    volumes:
      - ./docker:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  db:
    driver: bridge

volumes:
  db:


